### ISSUE TITLE
May Newsletter suggestion: k256 crate

### ISSUE THREAD

**Issue by tarcieri** [rust-in-blockchain/rust-in-blockchain#10]
I just announced the `k256` crate:

https://www.reddit.com/r/rust/comments/gbjsr9/ann_rustcrypto_p256_and_k256_v020_pure_rust_nist/

It's a pure Rust implementation of the curve/field arithmetic for secp256k1, the elliptic curve used by Bitcoin, Ethereum, etc.

It'd be great to get it in your newsletter! I can send a PR.

**Comment by Aimeedeer** [comment]
Very cool, thank you @tarcieri!

**Comment by brson** [comment]
Thanks @tarcieri for the suggestion. We'll cover this along with some of your other recent work in the newsletter.
