### ISSUE TITLE
Update Anoma repos

### ISSUE THREAD

**Issue by cwgoes** [rust-in-blockchain/rust-in-blockchain#159]
Hi there,

Anoma Rust development is split into several repositories:
- [anoma/anoma](https://github.com/anoma/anoma) (temporarily dormant)
- [anoma/namada](https://github.com/anoma/namada) (active)
- [anoma/vamp-ir](https://github.com/anoma/vamp-ir) (active)
- [anoma/taiga](https://github.com/anoma/taiga) (active)

I think you're tracking only the first repository at the moment - would you like to track the others? Happy to aggregate statistics if it's helpful.

**Comment by Aimeedeer** [comment]
Thanks for the info! @cwgoes 

I've updated the Anoma section in the rib-bible: https://github.com/rust-in-blockchain/rust-in-blockchain/blob/master/rib-bible.md#anoma

Please feel free to make any changes if needed.
