### ISSUE TITLE
Interested in Hiring - Lava 

### ISSUE THREAD

**Issue by cdsdesilva** [rust-in-blockchain/rust-in-blockchain#180]
Hi Aimee,

Saw your work on GitHub, really impressive stuff. My company is interested in hiring a dev and would love to chat with you. 

Thanks,
Chan

**Comment by Aimeedeer** [comment]
Hi,

For hiring, you can add your open positions to the [job board](https://rustinblockchain.org/job-board/) by submitting a PR to the source page directly: https://github.com/rust-in-blockchain/rust-in-blockchain/blob/master/content/job-board.md 

I'll close this issue.
