### ISSUE TITLE
Zebra is developed by a team

### ISSUE THREAD

**Issue by hdevalence** [rust-in-blockchain/Rust-in-Blockchain#3]
Hey, thanks for mentioning the Zebra development work in the newsletter.  It may be too late to change the email, but I wanted to note that Zebra isn't developed just by me as the text suggests but by a team (me and @dconnolly).  It would be great if that were corrected in the version that lives in the repo, and maybe next time feel free to reach out beforehand? We'd be happy to talk about the stuff we're working on.

**Comment by Aimeedeer** [comment]
Thanks for reminding us and making the correction. We have just updated the information on GitHub and the site page to credit @dconnolly. Sorry for the oversight.
